#!/usr/bin/env node
/* PHANG Command Line Tool
 * Usage: ./phang [command]
 * 
 *
 *
 */

// Slice away the setup of the command line:
var args = process.argv.slice(2);

//console.log(args);

//var fs = require("fs");
//var data = fs.readFileSync("web/app.php", "utf8");

//console.log(data);


var sys = require('sys')
var exec = require('child_process').exec;
function puts(error, stdout, stderr) { console.log(stdout) }
exec("php php/Phang.php " + args[0], puts);
